[programs.devnet]
myepicproject = "Bggy2xycNXFfLaLaEbn7Bnp5LXPjAxGN8wTPuqcA5fay"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/matthewtang/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
